import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import ProjectsComponent from '../components/project/ProjectItem'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>NazaAdimoha | MERN-STACK Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <ProjectsComponent />
      <Contact />
    </div>
  )
}
